### PR TITLE
Hide search bar

### PR DESCRIPTION
**Pull request by martmists**
gif

Credits to TheBITLINK

### CODE REVIEW

**Comment by martmists** [comment]
First of all, how am I supposed to make it only show the one commit AFTER I updated from this branch?
Secondly, as the gif shows the ending animation is a bit meh, feel free to fix

I'll wait for some feedback until merging.

**Comment by AlexFlipnote** [comment]
this

**Comment by martmists** [comment]
I meant like how do I make it show like this  and not like this

**Comment by AlexFlipnote** [comment]
Oh, quite unsure actually

**Pull request merged**
